import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: '#121212' },
    container: { flex: 1, backgroundColor: '#121212', position: 'relative' },
    form: {
        width: '90%',
        alignSelf: 'center',
        padding: 20,
        backgroundColor: '#1a1a1a',
        borderRadius: 15,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 20,
        position: 'absolute',
    },
    input: {
        backgroundColor: '#222',
        color: 'white',
        width: '100%',
        padding: 16,
        borderRadius: 10,
        fontSize: 16,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: '#333',
    },
    button: {
        backgroundColor: '#1e90ff',
        paddingVertical: 15,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 50,
    },
    buttonDisabled: { backgroundColor: '#1e90ff80' },
    buttonText: { color: 'white', fontWeight: 'bold', fontSize: 16 },
    flatList: { flex: 1, backgroundColor: '#121212' },
    thumbContainer: {
        flex: 1,
        margin: 8,
        backgroundColor: '#222',
        borderRadius: 10,
        overflow: 'hidden',
        borderWidth: 2,
        borderColor: '#333',
        maxWidth: '48%',
    },
    thumbSelected: { borderColor: '#1e90ff', backgroundColor: '#1e1e3c' },
    thumbPlaceholder: {
        flex: 1,
        margin: 8,
        maxWidth: '48%',
        backgroundColor: 'transparent',
    },
    thumbnail: { width: '100%', aspectRatio: 16 / 9 },
    qualityLabel: {
        color: 'white',
        textAlign: 'center',
        padding: 8,
        fontSize: 14,
        backgroundColor: '#00000080',
    },
    downloadButton: {
        backgroundColor: '#1e90ff',
        padding: 16,
        borderRadius: 12,
        alignItems: 'center',
        marginTop: 10,
        marginHorizontal: 10,
    },
    downloadText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
    loadingIndicator: {
        position: 'absolute',
        top: '50%',
        left: '50%',
        marginLeft: -20,
        marginTop: -20,
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingTop: 100,
    },
    emptyText: { color: '#888', textAlign: 'center', fontSize: 16 },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.6)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    modalContainer: {
        width: '100%',
        maxWidth: 340,
        backgroundColor: '#1f1f1f',
        borderRadius: 20,
        padding: 25,
        alignItems: 'center',
        borderWidth: 1,
    },
    modalSuccess: {
        borderColor: '#2ecc71',
        backgroundColor: '#1a1f24',
    },
    modalError: {
        borderColor: '#e74c3c',
        backgroundColor: '#1a1a1f',
    },
    modalInfo: {
        borderColor: '#3498db',
        backgroundColor: '#1a1f2a',
    },
    modalIcon: {
        fontSize: 42,
        marginBottom: 15,
    },
    modalTitle: {
        color: '#fff',
        fontSize: 22,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 8,
    },
    modalMessage: {
        color: '#ddd',
        fontSize: 16,
        textAlign: 'center',
        lineHeight: 22,
        marginBottom: 20,
    },
    modalButton: {
        backgroundColor: '#1e90ff',
        paddingVertical: 12,
        paddingHorizontal: 35,
        borderRadius: 10,
        marginTop: 10,
    },
    modalButtonText: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 16,
    },
});